s4:
  enabled: true
  base_url: "https://ALINHANA21.bristlecone.com:44307"
  service: "API_SALES_ORDER_SRV"
  username: "TRAIN_51_S21"
  password: "Integration@123"

ibp:
  enabled: true
  base_url: "https://my400230-api.scmibp.ondemand.com/sap/opu/odata/sap/"
  service: "IBP_APP_JOB_EXTERNAL"
  username: "Richard.m@bristlecone.com"
  password: "Monday@1234"
  planning_area: "HPA2508"
  key_figure: "I_SALESORDERREQUEST"
  planning_level: "I_DAYPRODLOCDEMAND"
