s4:
  enabled: true
  base_url: "https://ALINHANA21.bristlecone.com:44307"
  service: "API_SALES_ORDER_SRV"
  username: "TRAIN_51_S21"
  password: "Integration@123"

ibp:
  enabled: true
  base_url: "https://my400230-api.scmibp.ondemand.com"
  service: "IBP/PLANNING_DATA_API_SRV/"
  username: "IBP_FILE_CI"
  password: "IbpApiconn@123456789"


  #planning_area: "HPA2508"
  #key_figure: "I_SALESORDERREQUEST"
  #planning_level: "I_DAYPRODLOCDEMAND"
 